### ISSUE TITLE
Waiting needlessly long time before reading sensor value?

### ISSUE THREAD

**Issue by mmilata** [jaques/sht21_python#4]
The datasheet says that it should take at most 85ms for the temperature and 29ms for the humidity value to become available (datasheet v4, page 9, table 7). Here, however, the wait is 250ms for both.

My experience with electronics is essentially zero, so perhaps it's standard practice to have this large safety margin? Consider this more of a question than a bug report:) I've been polling my sensor with 86ms/30ms delay every 2 seconds past week and encountered no problem so far, though.

**Comment by jaques** [comment]
Looking through the data sheet I agree with you.  I've updated the code to bring it into line with your version I found whilst grabbing your fork.  Thanks for letting me know.

**Comment by jaques** [comment]
oh... I hope you don't mind me copying the couple of lines over, I couldn't find a licence... please let me know if you have any concerns.

**Comment by mmilata** [comment]
Haven't decided on the license yet - feel free to copy anything in the meantime.
